// <auto-generated />
namespace Inventory.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addnewErorrtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnewErorrtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201903081903389_add-new-Erorr-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
